### ISSUE TITLE
doesn't work with nest.js 7

### ISSUE THREAD

**Issue by shierro** [wpkyoto/serverless-lambda-nestjs#4]
Hi! I just tried with your sample. I got this on a windows machine

![ScreenShot_20200512003542](https://user-images.githubusercontent.com/12129589/81586752-9e8da480-93e8-11ea-97c1-08c3a7a613fb.png)

**Comment by shierro** [comment]
this is a sample code
https://github.com/shierro/nestjs-serverless

You can get error when running `yarn sls`

**Comment by hideokamoto** [comment]
Try to replace the code in `src/index.ts`

```typescript
import { APIGatewayProxyHandler } from 'aws-lambda';

export const handler: APIGatewayProxyHandler = async (event, context) => {
  return {
    event
  }
};
```

The error still occurred.

```bash
% NODE_ENV=local STAGE=staging sls offline start --env=local
Serverless: Compiling with Typescript...
Serverless: Using local tsconfig.json
Serverless: Typescript compiled.
Serverless: Watching typescript files...
offline: Starting Offline: staging/ap-southeast-2.
offline: Offline [http for lambda] listening on http://localhost:3002
 
  Type Error ---------------------------------------------
 
  TypeError: path.startsWith is not a function
      at HttpServer.createRoutes (/Users/sandbox/nestjs-serverless/node_modules/serverless-offline/dist/events/http/HttpServer.js:265:25)
      at Http._create (/Users/sandbox/nestjs-serverless/node_modules/serverless-offline/dist/events/http/Http.js:41:65)
      at /Users/sandbox/nestjs-serverless/node_modules/serverless-offline/dist/events/http/Http.js:50:12
      at Array.forEach (<anonymous>)
      at Http.create (/Users/sandbox/nestjs-serverless/node_modules/serverless-offline/dist/events/http/Http.js:45:12)
      at ServerlessOffline._createHttp (/Users/sandbox/nestjs-serverless/node_modules/serverless-offline/dist/ServerlessOffline.js:214:53)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)
      at async Promise.all (index 0)
      at ServerlessOffline.start (/Users/sandbox/nestjs-serverless/node_modules/serverless-offline/dist/ServerlessOffline.js:129:5)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.9.1
     Framework Version:         1.61.2
     Plugin Version:            3.2.7
     SDK Version:               2.3.0
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
 
Serverless: Compiling with Typescript...
Serverless: Typescript compiled.
```

It's not `serverless-lambda-nestjs`'s problem.

**Comment by shierro** [comment]
@hideokamoto you're right. thanks for the tip! i think it must have something to do with serverless-offline project. 

Have you tried to set-up a working offline development workflow with library `serverless-lambda-nestjs`?

**Comment by hideokamoto** [comment]
We're using serverless-offline to development it.

Example: https://github.com/hideokamoto/serverless-lambda-nestjs/tree/master/examples/simple-api

```
$ git clone https://github.com/hideokamoto/serverless-lambda-nestjs.git
$ cd serverless-lambda-nestjs
// Build the package
$ npm install
$ npm run build

// Move to example pj
$ cd examples/simple-api
$ npm install
$ sls offline
```

**Comment by hideokamoto** [comment]
![スクリーンショット 2020-05-12 19 06 06](https://user-images.githubusercontent.com/6883571/81671203-b6663680-9483-11ea-8a74-c3f8131ccb1e.png)
